### ISSUE TITLE
Clone::clone() policy

### ISSUE THREAD

**Issue by adlerd** [dpbriggs/convenient-skiplist#2]
This crate seems to do a lot of seemingly-unnecessary clones; for example,

```rust
if count >= self.len() {
    // let new = SkipList::new();
    // let garbage = std::mem::replace(&mut self, &mut new);
    // drop(garbage);
    let ret = self.iter_all().cloned().collect();
    *self = SkipList::new(); // TODO: Does this drop me?
    return ret;
}
```

Are these considered just artifacts of a "work in progress" or are they intended to be part of the permanent performance characteristics of this crate for API reasons?

**Comment by dpbriggs** [comment]
Thanks for taking interest!

It is part work in progress, part design, and part API design.

The two big areas we clone are:

1. In the skiplist itself, as every node carries a copy of value.
2. Simple API design encourages returning `T`.

The first one can likely be fixed by using an `Rc` instead of cloning the value at every node. I don't think that will cause too many issues.

The second reason is more complex.

We currently store values in `NodeValue<T>`, which itself is boxed. As far as I can tell, there is no clean way to get `T` without public wrapper types and Deref. I would like to be wrong here.

For example, `pop_back` should return something like `Option<T>`, but I'm not sure of a good way to do that without cloning. We actually have the heap allocated value in our hands before we return, but opt to clone and drop it -- would love your opinion here. Maybe some sort of a public `pub struct Value(T)` which implements `Deref`? I'm worried that would get confusing, as the signature is now `Option<Value<T>>`.

The example given is pure convenience plus the issue above. We already own the bottom row of the skiplist, so we could presumably return some form of it to prevent cloning. I'm comfortable using the aforementioned `Value(T)` type and returing an `impl Iterator` to prevent cloning, but would need to design that first.

What are your thoughts?

**Comment by adlerd** [comment]
> In the skiplist itself, as every node carries a copy of value.

Okay, yeah, this is exactly what I was looking for before I went in and said "you can definitely delete all your `clone()`s". But now I want to take a closer look at how this is implemented. Note that even though it looks like an implementation detail, this fact is actually part of your public API in the presence of a type containing something like `Rc<Cell<T>>` but whose `Clone::clone()` actually does a deep clone: parts of the skiplist could end up with different values.

**Comment by dpbriggs** [comment]
Yep! I originally intended to use the skiplist for Copy types, but after a thousand lines it was too expensive to change so I settled with Clone.

Pretty much every public and private skiplist impl here requires the `Clone` bound, so it's going to be an involved refactor.

I'll avoid using `Cell` as it's well defined when values are read and accessed. I can probably get away with `Rc<T>`, whose clone is shallow.

It will be interesting to see if this will faster. Doing ~100 inserts is microsecond territory, and it may be able to drop that lower.

**Comment by dpbriggs** [comment]
Phew, one degree and a pandemic later, I think it's best to leave the library as it is. 

I'm thinking it's best to have a SkiplistRef type for those who want to opt-in to that behaviour. It's not clear when I'll get the time to work on that, so I'll pre-emptively close the ticket.

Thank you for starting this discussion @adlerd! It's been fun to think about to restructure the program.
